name: pikaday
description: package:js bindings for the Pikaday date picker by David Bushnell
version: 2.0.0
author: John Ryan <john.p.ryan4@gmail.com>
homepage: https://github.com/johnpryan/pikaday-dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  js: ">=0.6.0 <1.0.0"

dev_dependencies:
  test: ^1.3.0
  build_web_compilers: any
  build_runner: any
